sonar.projectKey=urlshortener-capstone
sonar.projectName=URL Shortener Capstone
sonar.host.url=http://localhost:9000
sonar.sources=go-service,python-service,node-service
sonar.exclusions=**/node_modules/**,**/venv/**,**/*.db,**/templates/**
sonar.qualitygate.wait=true