apiVersion: v1
kind: Service
metadata:
  name: {{ include "urlshortener.fullname" . }}-python
  labels:
    app.kubernetes.io/component: python
    {{- include "urlshortener.labels" . | nindent 4 }}
spec:
  type: {{ .Values.pythonService.service.type }}
  ports:
    - port: {{ .Values.pythonService.service.port }}
      targetPort: 5000
      protocol: TCP
  selector:
    app.kubernetes.io/component: python
    {{- include "urlshortener.selectorLabels" . | nindent 4 }}