apiVersion: v1
kind: Secret
metadata:
  name: {{ include "urlshortener.fullname" . }}-secrets
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  DUMMY_SECRET: "capstone-local-only"